name: Vanilla

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!

      - name: install
        working-directory: ./vanilla
        run: yarn install

      - name: build
        working-directory: ./vanilla
        run: yarn run build
